
variables:
  GIT_STRATEGY: fetch

cache:
    paths:
    - .cache/

BM_combination_tests:
  stage: test
  script:
    - pytest --ff "Tests/BM combinations" -n 2
  tags:
    - ams
    - python

application_load_tests:
  stage: test
  script:
    - pytest --ff --only-load Tests/Applications 
  tags:
    - ams
    - python

other_tests:
  stage: test
  script:
    - pytest "--ignore=Tests/BM combinations" --ignore=Tests/Applications --ff Tests
  tags:
    - ams
    - python

Full_application_tests:
  stage: test
  script:
    - pytest --ff Tests/Applications -n 4
  when: manual
  tags:
    - ams
    - python

    

    