
variables:
  GIT_STRATEGY: fetch

cache:
    paths:
    - .cache/

BM_combination_tests:
  stage: test
  script:
    - pytest --ff "Tests/BM combinations" -n 2
  tags:
    - ams
    - python

other_tests:
  stage: test
  script:
    - pytest "--ignore=Tests/BM combinations" --ignore=Tests/Applications --ff Tests
  tags:
    - ams
    - python

Application_tests:
  stage: test
  script:
    - pytest --ff Tests/Applications -n 4 --timeout=1700
  tags:
    - ams
    - python

    

    