name: sphinx

channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - sphinx
  - make
  - myst-parser
  - cloud_sptheme
  - pygments_anyscript
  - matplotlib
  - pillow
  - pip:
    - sphinxext-opengraph
