name: Nightly Full AMMR tests

on:
  schedule:
    - cron: 0 3 * * *
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened]
  

jobs:
  test:
    runs-on: self-hosted
    if: contains(github.event.comment.body, '#Run full test') || github.event_name == 'schedule'
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          cd Tests
          pytest --runslow -n 4 --instafail 

  
