name: Nightly Full AMMR tests

on:
  schedule:
    - cron: 0 3 * * *
  pull_request_review_comment:
    types: [created, edited]
  pull_request:
    types: [opened]
  workflow_dispatch:

concurrency: 
  group: ci-${{ github.ref }}
  cancel-in-progress: true


jobs:
  test:
    runs-on: [self-hosted, AnyBody]
    if: contains(github.event.comment.body, '#Run full test') || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'

    env:
      # Triggers a warning at 20 deg muscles angles
      ShortestPathMaxAngle: 0.3491
   

    strategy:
      fail-fast: false
          
    steps:
      - uses: actions/checkout@v2

      - name: Install conda
        run: | 
          Invoke-Webrequest -URI https://anaconda.org/conda-forge/micromamba/0.15.2/download/win-64/micromamba-0.15.2-0.tar.bz2 -OutFile ~\micromamba.tar.bz2
          (Get-FileHash ~\micromamba.tar.bz2).hash -eq "d406ee990640123b05b5b55a720720513d3ad8eed6d3377324e4842c6f141308"
          C:\PROGRA~1\Git\usr\bin\tar.exe -xvjf ~/micromamba.tar.bz2 --strip-components 2 -C ~ Library/bin/micromamba.exe
          echo "MAMBA_ROOT_PREFIX=~\micromamba" >> $GITHUB_ENV

      - name: Create conda environment
        run: | 
          ~\micromamba.exe shell hook -s powershell | Out-String | iex
          if (Test-Path -Path $MAMBA_ROOT_PREFIX\envs\_ammr_test) {$OPR = "update"} else {$OPR = "create"}
          micromamba env $OPR -y -n _ammr_test -f Tests\test-environment.yml


      - name: Run full AMMR tests
        run: |
          ~\micromamba.exe shell hook -s powershell | Out-String | iex
          micromamba activate _ammr_test

          cd Tests
          pytest --runslow -n 4 --instafail 

    
