name: Run AMMR tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths-ignore:
    - 'Docs/**'
  schedule:
    - cron: 0 3 * * *

jobs:
  test:

    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    
    steps:
      - uses: actions/checkout@v2

      - name: Nigthly Full AMMR tests
        if:  github.event_name == 'schedule'
        run: pytest -n 4 --instafail --runslow

      - name: AMMR tests (Fast)
        if:  github.event_name != 'schedule'
        run: pytest -n 4 --instafail

  
